/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * mainGame.ls
 */
export class mainGameSceneBase extends Laya.Scene {
    public deskNode: Laya.Image;
    public roomIdLabel: Laya.Label;
    public playerIdLabel: Laya.Label;
    public playerSeatLabel: Laya.Label;
}

